name: Test Workflow

on:
  push:
    branches:
      - production
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Message
        run: echo "Workflow is running!"